spring:
  datasource:
#    url: jdbc:h2:tcp://172.31.39.61/~/aikuDB
    url: jdbc:h2:tcp://localhost/~/Downloads/aikuTest
    username: sa
#    username: aiku
    password:
#    password: aiku
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size : 100
#        show_sql: true
        format_sql: true

jwt:
  secret: f48d729a72445f378eb3be26525615782ddd1555889c9997d41ddab82d560c51
#  공개 금지 (공개시 ignore에 추가 필요)
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type : trace
logging:
  level:
#    root: trace
  org.hibernate.type: trace

server:
  port: 443
  ssl:
    key-store: keystore.p12
#    key-store: /home/ubuntu/aiku_backend/AiKu_backend/aiku/keystore.p12
    key-store-type: PKCS12
    key-store-password: aiku1234